Update HPA to new api autoscaling v2
benthosdev/benthos-helm-chart pull request #58
Opened 2023-11-27 22:02 UTC by bhataprameya

Update HPA to new api autoscaling v2

2023-11-30 15:55 UTC, charlie-haley requested changes

2023-11-30 15:55 UTC, charlie-haley commented on templates/hpa.yaml
> +apiVersion: autoscaling/v2
Could you add a conditional check here, just so the chart still supports some older versions - e.g 

```
{{- if semverCompare ">=1.23.0-0" .Capabilities.KubeVersion.Version }}
```

2023-11-30 23:15 UTC, bhataprameya commented on templates/hpa.yaml
> +apiVersion: autoscaling/v2
Updated PR

2023-12-07 20:12 UTC, charlie-haley approved these changes
LGTM

2023-12-07 20:12 UTC, merged